name = "app"
version = "1.0.0"
description = "A Wisp example"
gleam = ">= 0.32.0"

[dependencies]
wisp = { path = "../.." }
gleam_erlang = ">= 0.25.0 and < 1.0.0"
mist = ">= 1.2.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_stdlib = ">= 0.39.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"
