name = "app"
version = "1.0.0"
description = "A Wisp example"
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = "~> 0.30"
wisp = { path = "../.." }
gleam_json = "~> 0.6"

[dev-dependencies]
gleeunit = "~> 0.10"
