name = "wisp"
version = "0.4.0"
gleam = ">= 0.30.0"
description = "A fun and practical web framework for Gleam"
licences = ["Apache-2.0"]

repository = { type = "github", user = "lpil", repo = "wisp" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = "~> 0.29"
gleam_http = "~> 3.5"
mist = "~> 0.13"
simplifile = "~> 0.1"
gleam_crypto = "~> 0.4"
exception = "~> 1.0"
gleam_json = "~> 0.6"

[dev-dependencies]
gleeunit = "~> 0.10"
