name = "wisp"
version = "0.9.0"
gleam = ">= 0.32.0"
description = "A practical web framework for Gleam"
licences = ["Apache-2.0"]

repository = { type = "github", user = "gleam-wisp", repo = "wisp" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
exception = "~> 1.0"
gleam_crypto = "~> 1.0"
gleam_erlang = "~> 0.21"
gleam_http = "~> 3.5"
gleam_json = "~> 0.6"
gleam_stdlib = "~> 0.29 or ~> 1.0"
mist = "~> 0.13"
simplifile = "~> 1.0"
marceau = "~> 1.1"

[dev-dependencies]
gleeunit = "~> 1.0"
