name = "app"
version = "1.0.0"
description = "A Wisp example"
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = "~> 0.30"
wisp = { path = "../.." }
gleam_erlang = "~> 0.23"
mist = ">= 4.0.0 and < 5.0.0"


[dev-dependencies]
gleeunit = "~> 1.0"
