name = "app"
version = "1.0.0"
description = "A Wisp example"
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
promgleam = ">= 0.2.0 and < 1.0.0"
wisp = ">= 0.15.0 and < 1.0.0"
mist = ">= 1.2.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
