name = "app"
version = "1.0.0"
description = "A Wisp example"
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = "~> 0.30"
wisp = { path = "../.." }
mist = ">= 2.0.0 and < 3.0.0"
gleam_erlang = "~> 0.23"

[dev-dependencies]
gleeunit = "~> 1.0"
